#!/usr/bin/env python3
"""Assemble a single markdown + HTML notebook from the other examples."""

from __future__ import annotations

from pathlib import Path

from _util import OUTPUT_DIR, ROOT, parser
from zuco_lab.reports import html_page, md_table_to_html, write_text

from importlib import import_module

SECTIONS = [
    ("01_repo_inventory", "01_repo_inventory"),
    ("02_subject_alignment", "02_subject_alignment"),
    ("03_reader_agreement", "03_reader_agreement"),
    ("04_label_conditioned_gaze", "04_label_conditioned_gaze"),
    ("05_word_sentence_bridge", "05_word_sentence_bridge"),
    ("06_split_and_schema", "06_split_and_schema"),
    ("07_test_loop_bug", "07_test_loop_bug"),
    ("08_cpu_fusion", "08_cpu_fusion"),
    ("09_gaze_baselines", "09_gaze_baselines"),
    ("10_provo_preview", "10_provo_preview"),
]


def _collect() -> list[tuple[str, str]]:
    parts: list[tuple[str, str]] = []
    for mod_name, _ in SECTIONS:
        module = import_module(mod_name)
        parts.append((mod_name, module.build()))
    return parts


def _to_html_body(md: str) -> str:
    chunks: list[str] = []
    buf: list[str] = []
    in_code = False
    lines = md.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            if in_code:
                chunks.append("<pre>" + "\n".join(buf) + "</pre>")
                buf = []
                in_code = False
            else:
                in_code = True
            i += 1
            continue
        if in_code:
            buf.append(line)
            i += 1
            continue
        if line.startswith("|"):
            table_lines = []
            while i < len(lines) and lines[i].startswith("|"):
                table_lines.append(lines[i])
                i += 1
            chunks.append(md_table_to_html("\n".join(table_lines)))
            continue
        if line.startswith("# "):
            chunks.append(f"<h2>{line[2:]}</h2>")
        elif line.startswith("## "):
            chunks.append(f"<h3>{line[3:]}</h3>")
        elif line.startswith("### "):
            chunks.append(f"<h4>{line[4:]}</h4>")
        elif line.startswith("**") or line:
            chunks.append(f"<p>{line}</p>" if line else "")
        i += 1
    return "\n".join(chunks)


def build_all() -> tuple[str, str]:
    parts = _collect()
    md = [
        "# Personal lab notebook — Transformer Emotion Analysis with Gaze",
        "",
        "Generated by `examples/11_write_lab_notebook.py`. Stdlib only.",
        "",
        "The original training scripts are unchanged. This notebook is a reading",
        "layer on top of the checked-in CSVs: inventory, the subject-3 remapping,",
        "reader agreement, label-conditioned gaze, split integrity, the full-SST",
        "test-loop bug, and a CPU fusion wiring demo.",
        "",
    ]
    html_sections = [
        '<p class="sub">Generated from the stdlib examples. Training scripts are unchanged.</p>',
        '<div class="card warn"><strong>Read this first.</strong> '
        "Reader 3’s sentence ids are compacted after 149, and "
        "<code>model_full_SST.py</code> reports test metrics on the last batch only.</div>",
    ]
    for name, text in parts:
        md.append(f"<!-- source: examples/{name}.py -->")
        md.append(text)
        md.append("")
        html_sections.append(_to_html_body(text))
    return "\n".join(md), html_page("Personal gaze lab notebook", "\n".join(html_sections))


def main() -> None:
    parser("Write the combined markdown/HTML lab notebook.").parse_args()
    md, html = build_all()
    out_md = write_text(OUTPUT_DIR / "lab_notebook.md", md)
    out_html = write_text(OUTPUT_DIR / "lab_notebook.html", html)
    docs_md = write_text(ROOT / "docs" / "generated" / "lab_notebook.md", md)
    docs_html = write_text(ROOT / "docs" / "generated" / "lab_notebook.html", html)
    for path in (out_md, out_html, docs_md, docs_html):
        print(f"wrote {Path(path).relative_to(ROOT)}")


if __name__ == "__main__":
    main()
