"""Re-average ZuCo sentence-level subject files **by the `id` column**.

The original `get_average_sentence_level.py` concatenates frames and
`groupby(level=0)`. This script groups by `id` instead, treats zeros as
missing, and diffs against `average_data.csv`.

On this checkout the two averages match, because subject 3's `id` was
reset to 0–298 after the skips. That match is **not** proof the stimuli
are aligned. Compact id 150 is original sentence 250 for subject 3.
Use `realign_subject3.py` for the original-index remap.
"""

from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from common import (
    OUTPUT_DIR,
    ZUCO_AVERAGE_RAW,
    ensure_output_dir,
    read_csv,
    subject_sentence_paths,
    write_text,
)

FEATURE_COLS = [
    "SentLen",
    "omissionRate",
    "nFixations",
    "meanPupilSize",
    "GD",
    "TRT",
    "FFD",
    "SFD",
    "GPT",
]
ZERO_AS_MISSING = [c for c in FEATURE_COLS if c != "SentLen"]


def load_subjects() -> pd.DataFrame:
    frames = []
    for path in subject_sentence_paths():
        df = read_csv(path)
        df = df.copy()
        df["subject"] = int(path.stem.split("_")[0])
        df[ZERO_AS_MISSING] = df[ZERO_AS_MISSING].replace(0, np.nan)
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    all_rows = load_subjects()
    coverage = (
        all_rows.groupby("id")["subject"]
        .nunique()
        .rename("n_subjects")
        .reset_index()
    )
    coverage_counts = coverage["n_subjects"].value_counts().sort_index()

    averaged = all_rows.groupby("id")[FEATURE_COLS].mean().reset_index()
    averaged.to_csv(OUTPUT_DIR / "zuco_subject_mean_by_id.csv", index=False)
    coverage.to_csv(OUTPUT_DIR / "zuco_subject_coverage.csv", index=False)

    checked_in = read_csv(ZUCO_AVERAGE_RAW)
    merged = averaged.merge(checked_in, on="id", suffixes=("_by_id", "_checked"))

    max_abs = {}
    for col in FEATURE_COLS:
        diff = (merged[f"{col}_by_id"] - merged[f"{col}_checked"]).abs()
        max_abs[col] = float(diff.max())

    lines = [
        "# ZuCo subject aggregation by sentence id",
        "",
        "Generated by `examples/aggregate_subjects.py`.",
        "",
        f"- subject files: {len(subject_sentence_paths())}",
        f"- stacked rows: {len(all_rows)}",
        f"- unique sentence ids: {averaged['id'].nunique()}",
        "",
        "## How many subjects contribute to each sentence",
        "",
        "| n_subjects | n_sentences |",
        "| ---: | ---: |",
    ]
    for n_subj, n_sent in coverage_counts.items():
        lines.append(f"| {int(n_subj)} | {int(n_sent)} |")

    incomplete = coverage[coverage["n_subjects"] < 12]
    lines.extend(
        [
            "",
            f"Sentences with fewer than 12 subjects: {len(incomplete)}",
            "",
            "## Max |this script − checked-in average_data.csv|",
            "",
            "If these numbers are ~0, the checked-in average happened to match",
            "id-alignment (for example because missing subject-3 rows were still",
            "represented by NaNs that pandas skipped). If they are large, the",
            "checked-in file used positional `groupby(level=0)`.",
            "",
            "| feature | max abs diff |",
            "| --- | ---: |",
        ]
    )
    for col, value in max_abs.items():
        lines.append(f"| {col} | {value:.6f} |")
    lines.append("")

    out = OUTPUT_DIR / "aggregate_subjects.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print(f"Wrote {OUTPUT_DIR / 'zuco_subject_mean_by_id.csv'}")
    print("coverage:", coverage_counts.to_dict())
    print("max abs diffs:", {k: round(v, 6) for k, v in max_abs.items()})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
