"""Floors for the fusion experiments: majority class and gaze-only logistic regression.

A fusion model that cannot beat these numbers is not using the text encoder
(or is being scored on the last batch only — see docs/known-issues.md).
"""

from __future__ import annotations

import argparse

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from common import (
    LABEL_NAMES,
    OUTPUT_DIR,
    SST_FUSION_COLUMNS,
    SST_TEST,
    SST_TRAIN,
    ZUCO_COMBINED_STANDARD,
    ZUCO_FUSION_COLUMNS,
    ensure_output_dir,
    read_csv,
    write_text,
)


def _metrics(y_true, y_pred) -> dict[str, float]:
    return {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "precision_weighted": float(precision_score(y_true, y_pred, average="weighted", zero_division=0)),
        "recall_weighted": float(recall_score(y_true, y_pred, average="weighted", zero_division=0)),
        "f1_weighted": float(f1_score(y_true, y_pred, average="weighted", zero_division=0)),
        "f1_macro": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
    }


def _majority_predict(y_train: np.ndarray, n: int) -> np.ndarray:
    values, counts = np.unique(y_train, return_counts=True)
    return np.full(n, values[counts.argmax()])


def _gaze_pipeline() -> Pipeline:
    return Pipeline(
        [
            ("scaler", StandardScaler()),
            (
                "clf",
                LogisticRegression(
                    max_iter=2000,
                    solver="lbfgs",
                ),
            ),
        ]
    )


def _zuco_cv(df: pd.DataFrame) -> tuple[pd.DataFrame, str]:
    X = df[ZUCO_FUSION_COLUMNS].to_numpy(dtype=float)
    y = df["sentiment_label"].to_numpy(dtype=int)
    kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    rows = []
    reports = []
    for fold, (train_idx, test_idx) in enumerate(kf.split(X, y), start=1):
        y_tr, y_te = y[train_idx], y[test_idx]
        maj = _majority_predict(y_tr, len(y_te))
        pipe = _gaze_pipeline()
        pipe.fit(X[train_idx], y_tr)
        pred = pipe.predict(X[test_idx])
        maj_m = _metrics(y_te, maj)
        gaze_m = _metrics(y_te, pred)
        rows.append({"fold": fold, "model": "majority", **maj_m})
        rows.append({"fold": fold, "model": "gaze_logreg", **gaze_m})
        reports.append(
            f"### Fold {fold}\n\n"
            f"majority: acc={maj_m['accuracy']:.4f} f1w={maj_m['f1_weighted']:.4f}\n\n"
            f"gaze-only: acc={gaze_m['accuracy']:.4f} f1w={gaze_m['f1_weighted']:.4f}\n\n"
            "```\n"
            + classification_report(
                y_te, pred, target_names=[LABEL_NAMES[i] for i in range(3)], zero_division=0
            )
            + "```\n"
        )
    return pd.DataFrame(rows), "\n".join(reports)


def _sst_holdout() -> tuple[dict, dict, np.ndarray, np.ndarray]:
    train = read_csv(SST_TRAIN)
    test = read_csv(SST_TEST)
    y_tr = train["sentiment_label"].to_numpy(dtype=int)
    y_te = test["sentiment_label"].to_numpy(dtype=int)
    maj = _majority_predict(y_tr, len(y_te))
    pipe = _gaze_pipeline()
    pipe.fit(train[SST_FUSION_COLUMNS].to_numpy(dtype=float), y_tr)
    pred = pipe.predict(test[SST_FUSION_COLUMNS].to_numpy(dtype=float))
    return _metrics(y_te, maj), _metrics(y_te, pred), y_te, pred


def _cm_md(y_true, y_pred, title: str) -> list[str]:
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1, 2])
    names = [LABEL_NAMES[i] for i in range(3)]
    lines = [f"### {title}", "", "| gold \\ pred | " + " | ".join(names) + " |"]
    lines.append("| --- | " + " | ".join(["---:" ] * 3) + " |")
    for i, name in enumerate(names):
        cells = [str(int(v)) for v in cm[i]]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    lines.append("")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    zuco = read_csv(ZUCO_COMBINED_STANDARD)
    zuco_rows, zuco_fold_md = _zuco_cv(zuco)
    zuco_rows.to_csv(OUTPUT_DIR / "dummy_baseline_zuco_folds.csv", index=False)
    zuco_mean = zuco_rows.groupby("model")[
        ["accuracy", "precision_weighted", "recall_weighted", "f1_weighted", "f1_macro"]
    ].mean()

    sst_maj, sst_gaze, sst_y, sst_pred = _sst_holdout()

    lines = [
        "# Dummy baselines",
        "",
        "Generated by `examples/dummy_baseline.py`.",
        "",
        "ZuCo uses the same `StratifiedKFold(n_splits=5, random_state=42)` as",
        "`model_ZuCo_SST.py`. SST uses the checked-in train/test files.",
        "",
        "## ZuCo mean over 5 folds",
        "",
        "| model | accuracy | P_w | R_w | F1_w | F1_macro |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for model, row in zuco_mean.iterrows():
        lines.append(
            f"| {model} | {row['accuracy']:.4f} | {row['precision_weighted']:.4f} | "
            f"{row['recall_weighted']:.4f} | {row['f1_weighted']:.4f} | {row['f1_macro']:.4f} |"
        )
    lines.extend(["", "## ZuCo per-fold gaze-only reports", "", zuco_fold_md])
    lines.extend(
        [
            "## SST holdout",
            "",
            "| model | accuracy | P_w | R_w | F1_w | F1_macro |",
            "| --- | ---: | ---: | ---: | ---: | ---: |",
            f"| majority | {sst_maj['accuracy']:.4f} | {sst_maj['precision_weighted']:.4f} | "
            f"{sst_maj['recall_weighted']:.4f} | {sst_maj['f1_weighted']:.4f} | {sst_maj['f1_macro']:.4f} |",
            f"| gaze_logreg | {sst_gaze['accuracy']:.4f} | {sst_gaze['precision_weighted']:.4f} | "
            f"{sst_gaze['recall_weighted']:.4f} | {sst_gaze['f1_weighted']:.4f} | {sst_gaze['f1_macro']:.4f} |",
            "",
        ]
    )
    lines.extend(_cm_md(sst_y, sst_pred, "SST test confusion (gaze-only logreg)"))
    lines.extend(
        [
            "If `roberta_eye_tracking` on SST lands near the gaze-only row, the",
            "text encoder is not carrying the run (or the test loop is still",
            "scoring one batch). If it lands near majority, check class collapse.",
            "",
        ]
    )
    out = OUTPUT_DIR / "dummy_baseline.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print("ZuCo fold means:")
    print(zuco_mean.round(4).to_string())
    print("SST majority", {k: round(v, 4) for k, v in sst_maj.items()})
    print("SST gaze    ", {k: round(v, 4) for k, v in sst_gaze.items()})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
