"""Pearson correlations among fusion features.

High nFix–TRT / TRT–GD correlation is expected. A 16-d Linear on five
nearly collinear inputs is mostly learning a 1-d "how long did they look"
direction unless FFD or GPT break ranks.
"""

from __future__ import annotations

import argparse

import pandas as pd

from common import (
    OUTPUT_DIR,
    PRED_TEST_V2,
    SST_COMBINED,
    SST_FUSION_COLUMNS,
    ZUCO_COMBINED_STANDARD,
    ZUCO_FUSION_COLUMNS,
    ensure_output_dir,
    read_csv,
    write_text,
)


def _corr_md(title: str, corr: pd.DataFrame) -> list[str]:
    cols = list(corr.columns)
    lines = [f"## {title}", "", "|  | " + " | ".join(cols) + " |"]
    lines.append("| --- | " + " | ".join(["---:" ] * len(cols)) + " |")
    for idx in corr.index:
        cells = [f"{corr.loc[idx, c]:.3f}" for c in cols]
        lines.append(f"| {idx} | " + " | ".join(cells) + " |")
    lines.append("")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    zuco = read_csv(ZUCO_COMBINED_STANDARD)
    sst = read_csv(SST_COMBINED)
    pred = read_csv(PRED_TEST_V2)

    zuco_c = zuco[ZUCO_FUSION_COLUMNS].corr()
    sst_c = sst[SST_FUSION_COLUMNS].corr()
    pred_c = pred[SST_FUSION_COLUMNS].corr()

    zuco_c.to_csv(OUTPUT_DIR / "corr_zuco_fusion.csv")
    sst_c.to_csv(OUTPUT_DIR / "corr_sst_fusion.csv")
    pred_c.to_csv(OUTPUT_DIR / "corr_pred_word_fusion.csv")

    lines = [
        "# Fusion-feature correlations",
        "",
        "Generated by `examples/feature_correlations.py`.",
        "",
        "Pearson r. Predicted word-level gaze (`prediction_test_v2.csv`) is in",
        "predictor units, not milliseconds.",
        "",
    ]
    lines.extend(_corr_md("ZuCo sentence-level (measured, z-scored)", zuco_c))
    lines.extend(_corr_md("SST sentence-level (transferred, z-scored)", sst_c))
    lines.extend(_corr_md("Predicted SST word-level (`prediction_test_v2.csv`)", pred_c))
    lines.extend(
        [
            "## Reading",
            "",
            "- ZuCo measured features still show a strong TRT–GPT and nFixations–TRT",
            "  coupling because those measures share fixations.",
            "- If predicted SST correlations are *tighter* than ZuCo, the transfer",
            "  model is smoothing toward a one-factor reading-time signal. That",
            "  matches the linear clouds in `result/test_data_scatter_hist_plots.png`.",
            "",
        ]
    )
    out = OUTPUT_DIR / "feature_correlations.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print("ZuCo nFixations–TRT r =", round(float(zuco_c.loc["nFixations", "TRT"]), 3))
    print("SST nFix–TRT r =", round(float(sst_c.loc["nFix", "TRT"]), 3))
    print("Pred word nFix–TRT r =", round(float(pred_c.loc["nFix", "TRT"]), 3))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
