"""CPU-only walkthrough of the EyeTrackingModel tensor shapes.

Does not download BERT/RoBERTa. Uses a tiny random "encoder" so you can see
the concat geometry that `model_ZuCo_SST.py` implements:

    pooler_output [B, 768]
    gaze Linear    [B, 5] → [B, 16]
    concat         [B, 784]
    classifier     [B, 3]

Also applies the head to a few real ZuCo gaze rows with a frozen random
projection so the script touches real data without claiming accuracy.
"""

from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from common import (
    LABEL_NAMES,
    OUTPUT_DIR,
    ZUCO_COMBINED_STANDARD,
    ZUCO_FUSION_COLUMNS,
    ensure_output_dir,
    read_csv,
    write_text,
)

TEXT_DIM = 768
GAZE_IN = 5
GAZE_HIDDEN = 16
NUM_LABELS = 3


class NumpyEyeTrackingHead:
    """Minimal late-fusion head with the same widths as EyeTrackingModel."""

    def __init__(self, rng: np.random.Generator) -> None:
        # Xavier-ish scaling so logits stay finite.
        self.W_gaze = rng.normal(0, 1 / np.sqrt(GAZE_IN), size=(GAZE_IN, GAZE_HIDDEN))
        self.b_gaze = np.zeros(GAZE_HIDDEN)
        self.W_cls = rng.normal(
            0, 1 / np.sqrt(TEXT_DIM + GAZE_HIDDEN), size=(TEXT_DIM + GAZE_HIDDEN, NUM_LABELS)
        )
        self.b_cls = np.zeros(NUM_LABELS)

    def forward(self, pooler: np.ndarray, gaze: np.ndarray) -> dict[str, np.ndarray]:
        if pooler.ndim != 2 or pooler.shape[1] != TEXT_DIM:
            raise ValueError(f"pooler must be [B, {TEXT_DIM}], got {pooler.shape}")
        if gaze.ndim != 2 or gaze.shape[1] != GAZE_IN:
            raise ValueError(f"gaze must be [B, {GAZE_IN}], got {gaze.shape}")
        if pooler.shape[0] != gaze.shape[0]:
            raise ValueError("batch sizes differ")

        gaze_h = gaze @ self.W_gaze + self.b_gaze
        combined = np.concatenate([pooler, gaze_h], axis=1)
        logits = combined @ self.W_cls + self.b_cls
        # stable softmax
        shifted = logits - logits.max(axis=1, keepdims=True)
        exp = np.exp(shifted)
        probs = exp / exp.sum(axis=1, keepdims=True)
        return {
            "gaze_hidden": gaze_h,
            "combined": combined,
            "logits": logits,
            "probs": probs,
            "pred": probs.argmax(axis=1),
        }


def _shapes_report(batch: int, rng: np.random.Generator, head: NumpyEyeTrackingHead) -> list[str]:
    pooler = rng.normal(0, 0.02, size=(batch, TEXT_DIM))
    gaze = rng.normal(0, 1.0, size=(batch, GAZE_IN))
    out = head.forward(pooler, gaze)
    lines = [
        "## Random-batch shape check",
        "",
        f"- batch size: {batch}",
        f"- pooler_output: {pooler.shape}",
        f"- gaze input: {gaze.shape}",
        f"- gaze hidden (Linear 5→16): {out['gaze_hidden'].shape}",
        f"- concat: {out['combined'].shape}",
        f"- logits: {out['logits'].shape}",
        f"- softmax: {out['probs'].shape}",
        "",
        "Expected concat width: 768 + 16 = 784.",
        "",
    ]
    if out["combined"].shape != (batch, TEXT_DIM + GAZE_HIDDEN):
        raise RuntimeError("concat width drifted from the training scripts")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--batch", type=int, default=4)
    args = parser.parse_args()
    ensure_output_dir()

    rng = np.random.default_rng(args.seed)
    head = NumpyEyeTrackingHead(rng)

    zuco = read_csv(ZUCO_COMBINED_STANDARD)
    sample = zuco.head(8).copy()
    gaze = sample[ZUCO_FUSION_COLUMNS].to_numpy(dtype=float)
    # Stand-in pooled embeddings: deterministic per sentence_id so the demo is stable.
    pooler = np.stack(
        [
            np.random.default_rng(int(sid) + 17_771).normal(0, 0.02, size=TEXT_DIM)
            for sid in sample["sentence_id"]
        ]
    )
    result = head.forward(pooler, gaze)
    demo = sample[["sentence_id", "sentiment_label", "sentence"]].copy()
    demo["pred"] = result["pred"]
    for i, name in LABEL_NAMES.items():
        demo[f"p_{name}"] = result["probs"][:, i]
    demo.to_csv(OUTPUT_DIR / "fusion_demo_random_head.csv", index=False)

    lines = [
        "# Fusion architecture demo",
        "",
        "Generated by `examples/fusion_architecture_demo.py`.",
        "",
        "Random weights. Predictions are **not** a trained model.",
        "The point is the tensor geometry and that real ZuCo gaze rows load.",
        "",
        "```",
        "sentence ──► fake pooler [B, 768]",
        "gaze[5]  ──► Linear(5 → 16) ──► concat [B, 784] ──► Linear → 3",
        "```",
        "",
    ]
    lines.extend(_shapes_report(args.batch, rng, head))
    lines.extend(
        [
            "## First eight ZuCo rows through a frozen random head",
            "",
            "| sentence_id | gold | pred | p_neg | p_neu | p_pos | sentence |",
            "| ---: | --- | ---: | ---: | ---: | ---: | --- |",
        ]
    )
    for _, row in demo.iterrows():
        sent = str(row["sentence"]).replace("|", "\\|")
        lines.append(
            f"| {int(row['sentence_id'])} | {int(row['sentiment_label'])} | "
            f"{int(row['pred'])} | {row['p_negative']:.3f} | {row['p_neutral']:.3f} | "
            f"{row['p_positive']:.3f} | {sent} |"
        )
    lines.extend(
        [
            "",
            "If you later extract `EyeTrackingModel` into an importable module,",
            "replace `NumpyEyeTrackingHead` with the real `forward` and keep this",
            "script as a shape unit test.",
            "",
        ]
    )
    out = OUTPUT_DIR / "fusion_architecture_demo.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print(f"concat width ok: {TEXT_DIM + GAZE_HIDDEN}")
    print(demo[["sentence_id", "sentiment_label", "pred"]].to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
