"""Mean fusion-feature values by sentiment label.

This is not evidence that gaze *causes* sentiment. It is a sanity table:
if every class mean is identical, the concat head has nothing to work with
on that dataset (beyond per-row noise).
"""

from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from common import (
    LABEL_NAMES,
    OUTPUT_DIR,
    SST_COMBINED,
    SST_FUSION_COLUMNS,
    ZUCO_COMBINED_STANDARD,
    ZUCO_FUSION_COLUMNS,
    ensure_output_dir,
    read_csv,
    write_text,
)


def _profile(df: pd.DataFrame, cols: list[str], name: str) -> pd.DataFrame:
    rows = []
    for label, group in df.groupby("sentiment_label"):
        stats = group[cols].agg(["mean", "std"]).T
        for col in cols:
            rows.append(
                {
                    "dataset": name,
                    "label": int(label),
                    "label_name": LABEL_NAMES[int(label)],
                    "n": len(group),
                    "feature": col,
                    "mean": float(stats.loc[col, "mean"]),
                    "std": float(stats.loc[col, "std"]),
                }
            )
    return pd.DataFrame(rows)


def _extreme_rows(df: pd.DataFrame, cols: list[str], k: int = 3) -> pd.DataFrame:
    """Sentences with the largest L2 gaze vector (z-scored space)."""
    mag = np.sqrt((df[cols].to_numpy(dtype=float) ** 2).sum(axis=1))
    out = df[["sentence_id", "sentence", "sentiment_label"]].copy()
    out["gaze_l2"] = mag
    return out.sort_values("gaze_l2", ascending=False).head(k)


def _md_section(profile: pd.DataFrame, dataset: str) -> list[str]:
    lines = [f"## {dataset}", "", "| label | n | " + " | ".join(profile["feature"].unique()) + " |"]
    features = list(profile["feature"].unique())
    header_sep = "| --- | ---: | " + " | ".join(["---:" ] * len(features)) + " |"
    lines.append(header_sep)
    for label, group in profile.groupby("label"):
        group = group.set_index("feature")
        cells = [f"{group.loc[f, 'mean']:.3f} ± {group.loc[f, 'std']:.3f}" for f in features]
        n = int(group.iloc[0]["n"])
        lines.append(
            f"| {int(label)} ({LABEL_NAMES[int(label)]}) | {n} | " + " | ".join(cells) + " |"
        )
    lines.append("")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    zuco = read_csv(ZUCO_COMBINED_STANDARD)
    sst = read_csv(SST_COMBINED)
    zuco_prof = _profile(zuco, ZUCO_FUSION_COLUMNS, "zuco_standard")
    sst_prof = _profile(sst, SST_FUSION_COLUMNS, "sst_standard")
    combined = pd.concat([zuco_prof, sst_prof], ignore_index=True)
    combined.to_csv(OUTPUT_DIR / "gaze_feature_profiles.csv", index=False)

    zuco_ext = _extreme_rows(zuco, ZUCO_FUSION_COLUMNS)
    lines = [
        "# Gaze feature profiles",
        "",
        "Generated by `examples/gaze_feature_profiles.py`.",
        "",
        "Values are the same scaled units the training loaders use.",
        "",
    ]
    lines.extend(_md_section(zuco_prof, "ZuCo (`combined_sst_et_standard.csv`)"))
    lines.extend(_md_section(sst_prof, "SST (`combined_full_sst_et.csv`)"))
    lines.extend(
        [
            "## ZuCo sentences with the largest gaze L2",
            "",
            "These are the rows a randomly initialized gaze Linear will notice first.",
            "",
            "| sentence_id | label | gaze L2 | sentence |",
            "| ---: | --- | ---: | --- |",
        ]
    )
    for _, row in zuco_ext.iterrows():
        sent = str(row["sentence"]).replace("|", "\\|")
        lines.append(
            f"| {int(row['sentence_id'])} | {int(row['sentiment_label'])} "
            f"({LABEL_NAMES[int(row['sentiment_label'])]}) | "
            f"{row['gaze_l2']:.3f} | {sent} |"
        )
    lines.append("")
    out = OUTPUT_DIR / "gaze_feature_profiles.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print(f"Wrote {OUTPUT_DIR / 'gaze_feature_profiles.csv'}")
    print("ZuCo class means (nFixations, FFD, GPT, TRT, GD):")
    for label, group in zuco.groupby("sentiment_label"):
        means = group[ZUCO_FUSION_COLUMNS].mean().to_numpy()
        print(f"  {label} {LABEL_NAMES[int(label)]}: {np.round(means, 3)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
