#!/usr/bin/env python3
"""Rebuild examples/outputs/dataset_inventory.md from the live CSVs."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from examples.lib import features, io_csv, paths, report, schema


def inventory_rows() -> list[list[object]]:
    out = []
    for name, (rel, role) in paths.TABLES.items():
        path = paths.table_path(name)
        header = io_csv.read_header(path)
        rows = io_csv.read_rows(path)
        labels = ""
        if name in paths.SENTIMENT_TABLES:
            labs = features.labels_of(rows)
            counts = [labs.count(i) for i in (0, 1, 2)]
            labels = "/".join(str(c) for c in counts)
        out.append([name, rel, len(rows), len(header), labels or "—", role])
    return out


def main() -> int:
    table = report.markdown_table(
        ("name", "path", "rows", "cols", "neg/neu/pos", "role"),
        inventory_rows(),
    )
    body = report.join_sections(
        [
            "# Dataset inventory",
            "Generated by `examples/generate_markdown_tables.py` from the CSVs "
            "in this clone. Labels use "
            + ", ".join(f"{k}={v}" for k, v in schema.LABEL_NAMES.items())
            + ".",
            table,
            "Re-run with `--write` after replacing a CSV so the docs stay honest.",
        ]
    )
    # Always write this one — that is the script's job.
    from examples.lib.report import write_text

    dest = paths.OUTPUTS_DIR / "dataset_inventory.md"
    write_text(dest, body)
    print(body)
    print(f"\nwrote {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
