"""Print and write label histograms for ZuCo and SST splits.

SST is skewed (neutral is the minority). ZuCo is close to balanced.
The training scripts report weighted F1; this script shows why.
"""

from __future__ import annotations

import argparse

import pandas as pd

from common import (
    LABEL_NAMES,
    OUTPUT_DIR,
    SST_COMBINED,
    SST_TEST,
    SST_TRAIN,
    SST_VALID,
    ZUCO_COMBINED_STANDARD,
    ZUCO_TEST,
    ZUCO_TRAIN,
    ZUCO_VALID,
    ensure_output_dir,
    read_csv,
    write_text,
)


TABLES = [
    ("ZuCo combined (CV source)", ZUCO_COMBINED_STANDARD),
    ("ZuCo train.csv (unused by trainer)", ZUCO_TRAIN),
    ("ZuCo valid.csv (unused by trainer)", ZUCO_VALID),
    ("ZuCo test.csv (unused by trainer)", ZUCO_TEST),
    ("SST combined", SST_COMBINED),
    ("SST train", SST_TRAIN),
    ("SST valid", SST_VALID),
    ("SST test", SST_TEST),
]


def _hist(df: pd.DataFrame) -> pd.Series:
    counts = df["sentiment_label"].value_counts().sort_index()
    return counts.reindex([0, 1, 2], fill_value=0)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    rows = []
    lines = [
        "# Label distribution",
        "",
        "Generated by `examples/label_distribution.py`.",
        "",
        "| table | n | negative (0) | neutral (1) | positive (2) | majority | majority acc |",
        "| --- | ---: | ---: | ---: | ---: | --- | ---: |",
    ]

    for title, path in TABLES:
        df = read_csv(path)
        counts = _hist(df)
        n = int(counts.sum())
        majority_label = int(counts.idxmax())
        majority_acc = float(counts.max() / n)
        lines.append(
            f"| {title} | {n} | {int(counts.loc[0])} | {int(counts.loc[1])} | "
            f"{int(counts.loc[2])} | {majority_label} ({LABEL_NAMES[majority_label]}) "
            f"| {majority_acc:.4f} |"
        )
        rows.append(
            {
                "table": title,
                "n": n,
                "negative": int(counts.loc[0]),
                "neutral": int(counts.loc[1]),
                "positive": int(counts.loc[2]),
                "majority_label": majority_label,
                "majority_acc": majority_acc,
            }
        )

    lines.extend(
        [
            "",
            "Notes:",
            "",
            "- Majority accuracy is the floor for any classifier that ignores the text.",
            "- ZuCo `train/valid/test.csv` are **not** what `model_ZuCo_SST.py` uses;",
            "  that script re-splits the combined table with StratifiedKFold.",
            "- SST valid/test keep the same minority-neutral shape as train, so a",
            "  model that never predicts 1 can still post a mid-0.4 accuracy.",
            "",
        ]
    )
    out = OUTPUT_DIR / "label_distribution.md"
    write_text(out, "\n".join(lines))
    pd.DataFrame(rows).to_csv(OUTPUT_DIR / "label_distribution.csv", index=False)
    print(f"Wrote {out}")
    print(f"Wrote {OUTPUT_DIR / 'label_distribution.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
