"""Remap subject 3's compacted sentence ids and re-average ZuCo gaze.

`3_SR.csv` has 299 rows with `id` 0..298. That is **not** "sentences 0–298
exist and 299–399 are missing". `DataTransformer` drops original indices
150–249 and 399, then the export resets the frame index. Compact id maps
to original sentence index as:

    compact 0–149   → original 0–149
    compact 150–298 → original 250–398

Averaging the twelve files on the raw `id` column therefore mixes, for
example, everyone else's sentence 150 with subject 3's sentence 250.

This script writes a corrected subject-mean table and diffs it against
`ZuCo_et_csv_data/average_data.csv`.
"""

from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from common import (
    OUTPUT_DIR,
    ZUCO_AVERAGE_RAW,
    ZUCO_COMBINED_STANDARD,
    ensure_output_dir,
    read_csv,
    subject_sentence_paths,
    write_text,
)

FEATURE_COLS = [
    "SentLen",
    "omissionRate",
    "nFixations",
    "meanPupilSize",
    "GD",
    "TRT",
    "FFD",
    "SFD",
    "GPT",
]
ZERO_AS_MISSING = [c for c in FEATURE_COLS if c != "SentLen"]


def compact_id_to_original(compact_id: int) -> int:
    if compact_id <= 149:
        return compact_id
    return compact_id + 100


def load_aligned() -> pd.DataFrame:
    frames = []
    for path in subject_sentence_paths():
        df = read_csv(path).copy()
        subject = int(path.stem.split("_")[0])
        df["subject"] = subject
        if subject == 3:
            df["original_id"] = df["id"].astype(int).map(compact_id_to_original)
        else:
            df["original_id"] = df["id"].astype(int)
        df[ZERO_AS_MISSING] = df[ZERO_AS_MISSING].replace(0, np.nan)
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    aligned = load_aligned()
    coverage = (
        aligned.groupby("original_id")["subject"].nunique().rename("n_subjects").reset_index()
    )
    averaged = aligned.groupby("original_id")[FEATURE_COLS].mean().reset_index()
    averaged.to_csv(OUTPUT_DIR / "zuco_average_realigned.csv", index=False)
    coverage.to_csv(OUTPUT_DIR / "zuco_coverage_realigned.csv", index=False)

    checked = read_csv(ZUCO_AVERAGE_RAW).rename(columns={"id": "original_id"})
    merged = averaged.merge(checked, on="original_id", suffixes=("_realigned", "_checked"))

    diff_rows = []
    for col in FEATURE_COLS:
        delta = (merged[f"{col}_realigned"] - merged[f"{col}_checked"]).abs()
        diff_rows.append(
            {
                "feature": col,
                "max_abs_diff": float(delta.max()),
                "mean_abs_diff": float(delta.mean()),
                "n_changed": int((delta > 1e-9).sum()),
            }
        )
    diff_df = pd.DataFrame(diff_rows)
    diff_df.to_csv(OUTPUT_DIR / "zuco_realign_vs_checked.csv", index=False)

    coverage_counts = coverage["n_subjects"].value_counts().sort_index()
    missing = sorted(set(range(400)) - set(coverage["original_id"].astype(int)))

    # Which combined-table sentences sit on rows that change after realignment?
    changed_ids = set()
    for col in FEATURE_COLS:
        delta = (merged[f"{col}_realigned"] - merged[f"{col}_checked"]).abs()
        changed_ids.update(merged.loc[delta > 1e-9, "original_id"].astype(int).tolist())

    zuco = read_csv(ZUCO_COMBINED_STANDARD)
    touched = zuco[zuco["sentence_id"].isin(changed_ids)][
        ["sentence_id", "sentiment_label", "sentence"]
    ]

    lines = [
        "# Subject 3 realignment",
        "",
        "Generated by `examples/realign_subject3.py`.",
        "",
        "Compact → original map: `id <= 149` unchanged; `id + 100` otherwise.",
        "Original sentences **150–249 and 399** have no subject-3 row.",
        "",
        f"- aligned stacked rows: {len(aligned)}",
        f"- unique original ids present: {coverage['original_id'].nunique()}",
        f"- original ids with no subject at all: {missing}",
        "",
        "## Coverage after remapping",
        "",
        "| n_subjects | n_sentences |",
        "| ---: | ---: |",
    ]
    for n_subj, n_sent in coverage_counts.items():
        lines.append(f"| {int(n_subj)} | {int(n_sent)} |")

    eleven = coverage.loc[coverage["n_subjects"] < 12, "original_id"].astype(int)
    eleven_list = sorted(int(x) for x in eleven.tolist())
    expected_eleven = list(range(150, 250)) + [399]
    eleven_ok = eleven_list == expected_eleven
    lines.extend(
        [
            "",
            f"Original ids with 11 subjects: {len(eleven)}",
            f"Expected 150–249 and 399: {'yes' if eleven_ok else 'NO — ' + str(eleven_list[:12]) + '...'}",
            "",
            "## Diff vs checked-in `average_data.csv`",
            "",
            "| feature | max |abs| | mean |abs| | rows changed |",
            "| --- | ---: | ---: | ---: |",
        ]
    )
    for _, row in diff_df.iterrows():
        lines.append(
            f"| {row['feature']} | {row['max_abs_diff']:.6f} | "
            f"{row['mean_abs_diff']:.6f} | {int(row['n_changed'])} |"
        )
    lines.extend(
        [
            "",
            f"Original sentence ids whose mean gaze moves: {len(changed_ids)}",
            "",
            "Those ids include the 150–298 band, where subject 3's compact rows",
            "were previously averaged against the wrong stimuli, and 299–398,",
            "which pick up subject 3 only after the remap.",
            "",
            f"Labeled ZuCo sentences sitting on a changed id: {len(touched)}",
            "",
        ]
    )
    if len(touched):
        lines.extend(
            [
                "| sentence_id | label | sentence |",
                "| ---: | ---: | --- |",
            ]
        )
        for _, row in touched.sort_values("sentence_id").head(8).iterrows():
            sent = str(row["sentence"]).replace("|", "\\|")
            lines.append(
                f"| {int(row['sentence_id'])} | {int(row['sentiment_label'])} | {sent} |"
            )
        lines.append("")
        lines.append(f"(showing 8 of {len(touched)})")
        lines.append("")

    out = OUTPUT_DIR / "realign_subject3.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print("coverage", coverage_counts.to_dict())
    print("missing original ids", missing)
    print(diff_df.to_string(index=False))
    print(f"changed original ids: {len(changed_ids)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
