"""Mean-pool word-level predicted gaze and compare it to SST sentence rows.

`gaze_prediction/data/prediction_test_v2.csv` is 191,971 word rows.
`SST_data/combined_full_sst_et.csv` is 11,853 sentence rows with a 5-d
gaze vector already on it. This script asks a concrete question:

    If I average nFix/FFD/GPT/TRT/GD by sentence_id in the predicted
    word table, how close is that vector to the sentence table?

A high correlation means the checked-in SST gaze is (approximately) that
reducer. A low correlation means a different reducer or a different
predicted file was used.
"""

from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from common import (
    OUTPUT_DIR,
    PRED_TEST_V2,
    SST_COMBINED,
    SST_FUSION_COLUMNS,
    SST_WORD_PLACEHOLDER,
    ensure_output_dir,
    read_csv,
    write_text,
)


def _pearson(a: np.ndarray, b: np.ndarray) -> float:
    if a.std() == 0 or b.std() == 0:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    pred = read_csv(PRED_TEST_V2)
    placeholder = read_csv(SST_WORD_PLACEHOLDER)
    sst = read_csv(SST_COMBINED)

    reduced = pred.groupby("sentence_id", as_index=False)[SST_FUSION_COLUMNS].mean()
    counts = pred.groupby("sentence_id").size().rename("n_words").reset_index()
    reduced = reduced.merge(counts, on="sentence_id")

    # z-score the reduced vectors the same way SST combined looks (mean 0 std 1)
    zscored = reduced.copy()
    for col in SST_FUSION_COLUMNS:
        mu = zscored[col].mean()
        sd = zscored[col].std(ddof=0)
        zscored[f"{col}_z"] = (zscored[col] - mu) / (sd if sd else 1.0)

    merged = sst.merge(zscored, on="sentence_id", suffixes=("_sst", "_pred"))
    merged_raw = sst.merge(reduced, on="sentence_id", suffixes=("_sst", "_pred"))

    corr_z = {}
    corr_raw = {}
    for col in SST_FUSION_COLUMNS:
        corr_z[col] = _pearson(
            merged[f"{col}_sst"].to_numpy(dtype=float),
            merged[f"{col}_z"].to_numpy(dtype=float),
        )
        corr_raw[col] = _pearson(
            merged_raw[f"{col}_sst"].to_numpy(dtype=float),
            merged_raw[f"{col}_pred"].to_numpy(dtype=float),
        )

    skeleton_ok = len(pred) == len(placeholder)
    token_rate = float("nan")
    if skeleton_ok:
        token_rate = float(
            (
                placeholder["word"].fillna("").astype(str).reset_index(drop=True)
                == pred["word"].fillna("").astype(str).reset_index(drop=True)
            ).mean()
        )

    reduced.to_csv(OUTPUT_DIR / "predicted_gaze_sentence_mean.csv", index=False)

    lines = [
        "# Predicted-gaze sentence reduce",
        "",
        "Generated by `examples/reduce_predicted_gaze.py`.",
        "",
        f"- predicted word rows: {len(pred)}",
        f"- placeholder word rows: {len(placeholder)}",
        f"- same length: {skeleton_ok}; token equality: {token_rate:.4f}",
        f"- predicted sentence ids: {pred['sentence_id'].nunique()}",
        f"- SST combined rows: {len(sst)}",
        f"- inner-joined sentences: {len(merged)}",
        f"- predicted ids not in SST combined: "
        f"{pred['sentence_id'].nunique() - merged['sentence_id'].nunique()}",
        "",
        "## Pearson r (SST sentence column vs mean-pooled prediction)",
        "",
        "| feature | r (raw mean) | r (z-scored mean) |",
        "| --- | ---: | ---: |",
    ]
    for col in SST_FUSION_COLUMNS:
        lines.append(f"| {col} | {corr_raw[col]:.4f} | {corr_z[col]:.4f} |")

    word_stats = reduced["n_words"].describe()
    lines.extend(
        [
            "",
            "## Words per sentence in the predicted table",
            "",
            f"- mean {word_stats['mean']:.2f}, min {int(word_stats['min'])}, "
            f"max {int(word_stats['max'])}",
            "",
            "On this checkout the five z-scored correlations are far from 1.0",
            "(GD is near 0). The SST sentence gaze vector is therefore not a",
            "plain mean of `prediction_test_v2.csv`. Try a different reducer",
            "(max TRT, mean of content words only) or a different predicted file",
            "before treating the two tables as the same feature space.",
            "",
        ]
    )
    out = OUTPUT_DIR / "reduce_predicted_gaze.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print("joined", len(merged), "of SST", len(sst))
    print("r raw", {k: round(v, 4) for k, v in corr_raw.items()})
    print("r z   ", {k: round(v, 4) for k, v in corr_z.items()})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
