"""Run every example script and write a single summary.

Intended as the personal "docs still match the CSVs" check. No GPU, no
Hugging Face downloads, no network beyond what pandas needs for local files.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

from common import OUTPUT_DIR, ensure_output_dir, write_text

EXAMPLES_DIR = Path(__file__).resolve().parent

SCRIPTS = [
    "inspect_datasets.py",
    "schema_check.py",
    "label_distribution.py",
    "gaze_feature_profiles.py",
    "aggregate_subjects.py",
    "feature_correlations.py",
    "split_sanity_check.py",
    "word_level_preview.py",
    "fusion_architecture_demo.py",
    "dummy_baseline.py",
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    results = []
    overall = 0
    for name in SCRIPTS:
        script = EXAMPLES_DIR / name
        started = time.perf_counter()
        proc = subprocess.run(
            [sys.executable, str(script)],
            cwd=str(EXAMPLES_DIR.parent),
            capture_output=True,
            text=True,
            check=False,
        )
        elapsed = time.perf_counter() - started
        results.append(
            {
                "script": name,
                "returncode": proc.returncode,
                "seconds": elapsed,
                "stdout": proc.stdout,
                "stderr": proc.stderr,
            }
        )
        if proc.returncode != 0:
            overall = 1
        print(f"{name}: exit {proc.returncode} in {elapsed:.2f}s")
        if proc.returncode != 0 and proc.stderr:
            print(proc.stderr)

    lines = [
        "# Example suite summary",
        "",
        "Generated by `examples/run_all.py`.",
        "",
        "| script | exit | seconds |",
        "| --- | ---: | ---: |",
    ]
    for row in results:
        lines.append(f"| `{row['script']}` | {row['returncode']} | {row['seconds']:.2f} |")
    lines.extend(["", "## Captured stdout", ""])
    for row in results:
        lines.append(f"### `{row['script']}`")
        lines.append("")
        lines.append("```")
        lines.append((row["stdout"] or "").rstrip() or "(no stdout)")
        if row["stderr"]:
            lines.append("--- stderr ---")
            lines.append(row["stderr"].rstrip())
        lines.append("```")
        lines.append("")

    write_text(OUTPUT_DIR / "run_all_summary.txt", "\n".join(lines))
    print(f"Wrote {OUTPUT_DIR / 'run_all_summary.txt'}")
    return overall


if __name__ == "__main__":
    raise SystemExit(main())
