"""Fail if a documented table is missing columns, extra columns, or NaNs in keys.

This is the cheap guardrail before a training run: if someone re-exports a CSV
and drops `GPT` or renames `nFixations`, the fusion loaders will KeyError
halfway through tokenization.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field

import pandas as pd

from common import (
    EXPECTED_COLUMNS,
    EXPECTED_ROW_COUNTS,
    INVENTORY,
    OUTPUT_DIR,
    SST_FUSION_COLUMNS,
    ZUCO_COMBINED_STANDARD,
    ZUCO_FUSION_COLUMNS,
    ensure_output_dir,
    read_csv,
    write_text,
)


@dataclass
class Finding:
    key: str
    level: str
    message: str


@dataclass
class Report:
    findings: list[Finding] = field(default_factory=list)

    def add(self, key: str, level: str, message: str) -> None:
        self.findings.append(Finding(key, level, message))

    @property
    def errors(self) -> list[Finding]:
        return [f for f in self.findings if f.level == "error"]


def _check_columns(report: Report, key: str, df: pd.DataFrame) -> None:
    expected = EXPECTED_COLUMNS.get(key)
    if expected is None:
        report.add(key, "info", f"no frozen schema; columns={list(df.columns)}")
        return
    missing = [c for c in expected if c not in df.columns]
    extra = [c for c in df.columns if c not in expected]
    if missing:
        report.add(key, "error", f"missing columns: {missing}")
    if extra:
        report.add(key, "error", f"unexpected columns: {extra}")
    if not missing and not extra:
        report.add(key, "ok", "columns match the dictionary")


def _check_rows(report: Report, key: str, df: pd.DataFrame) -> None:
    expected = EXPECTED_ROW_COUNTS.get(key)
    if expected is None:
        return
    if len(df) != expected:
        report.add(key, "error", f"row count {len(df)} != {expected}")
    else:
        report.add(key, "ok", f"row count {len(df)}")


def _check_keys(report: Report, key: str, df: pd.DataFrame) -> None:
    for col in ("sentence_id", "id"):
        if col in df.columns:
            nnull = int(df[col].isna().sum())
            ndup = int(df[col].duplicated().sum())
            if nnull:
                report.add(key, "error", f"{col} has {nnull} NaNs")
            if ndup and key.endswith("combined_sst_et_standard.csv"):
                report.add(key, "error", f"{col} has {ndup} duplicates")
            elif ndup and key.endswith("ssts_ZuCo.csv"):
                report.add(key, "error", f"{col} has {ndup} duplicates")


def _check_fusion_complete(report: Report) -> None:
    zuco = read_csv(ZUCO_COMBINED_STANDARD)
    missing = zuco[ZUCO_FUSION_COLUMNS].isna().sum()
    if missing.any():
        report.add(
            "ZuCo_SST_data/combined_sst_et_standard.csv",
            "error",
            f"NaNs in fusion columns: {missing[missing > 0].to_dict()}",
        )
    else:
        report.add(
            "ZuCo_SST_data/combined_sst_et_standard.csv",
            "ok",
            "fusion columns have no NaNs",
        )

    sst = read_csv(INVENTORY["SST_data/combined_full_sst_et.csv"])
    missing = sst[SST_FUSION_COLUMNS].isna().sum()
    if missing.any():
        report.add(
            "SST_data/combined_full_sst_et.csv",
            "error",
            f"NaNs in fusion columns: {missing[missing > 0].to_dict()}",
        )
    else:
        report.add(
            "SST_data/combined_full_sst_et.csv",
            "ok",
            "fusion columns have no NaNs",
        )

    labels = sorted(zuco["sentiment_label"].unique().tolist())
    if labels != [0, 1, 2]:
        report.add(
            "ZuCo_SST_data/combined_sst_et_standard.csv",
            "error",
            f"unexpected label set {labels}",
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()
    report = Report()

    for key, path in INVENTORY.items():
        if not path.exists():
            report.add(key, "error", "file missing")
            continue
        header = None if path.name == "stts_all_sentence_level.csv" else "infer"
        if header is None:
            df = read_csv(path, header=None)
        else:
            df = read_csv(path)
        _check_columns(report, key, df)
        _check_rows(report, key, df)
        _check_keys(report, key, df)

    _check_fusion_complete(report)

    lines = ["# Schema check", "", "Generated by `examples/schema_check.py`.", ""]
    lines.append("| table | level | message |")
    lines.append("| --- | --- | --- |")
    for finding in report.findings:
        msg = finding.message.replace("|", "\\|")
        lines.append(f"| `{finding.key}` | {finding.level} | {msg} |")
    lines.append("")
    lines.append(f"errors: {len(report.errors)} / findings: {len(report.findings)}")
    out = OUTPUT_DIR / "schema_report.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print(f"findings={len(report.findings)} errors={len(report.errors)}")
    for finding in report.errors:
        print(f"ERROR {finding.key}: {finding.message}")
    return 1 if report.errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
