"""Confirm the checked-in holdout files are a partition, not a leaky sample.

Checks:
- ZuCo train/valid/test sentence_ids are disjoint and union to the combined table
- SST train/valid/test sentence_ids are disjoint and union to the combined table
- labels on the same sentence_id match across combined vs split files
- ssts_ZuCo.csv ids and labels match the combined ZuCo table
"""

from __future__ import annotations

import argparse

import pandas as pd

from common import (
    OUTPUT_DIR,
    SST_COMBINED,
    SST_TEST,
    SST_TRAIN,
    SST_VALID,
    ZUCO_COMBINED_STANDARD,
    ZUCO_SENTENCES,
    ZUCO_TEST,
    ZUCO_TRAIN,
    ZUCO_VALID,
    ensure_output_dir,
    read_csv,
    write_text,
)


def _partition(name: str, combined: pd.DataFrame, parts: dict[str, pd.DataFrame]) -> list[str]:
    lines = [f"## {name}", ""]
    combined_ids = set(combined["sentence_id"].tolist())
    part_ids = {key: set(df["sentence_id"].tolist()) for key, df in parts.items()}

    overlap_pairs = []
    keys = list(part_ids)
    for i, a in enumerate(keys):
        for b in keys[i + 1 :]:
            shared = part_ids[a] & part_ids[b]
            if shared:
                overlap_pairs.append((a, b, len(shared)))

    union = set().union(*part_ids.values())
    missing = combined_ids - union
    extra = union - combined_ids

    lines.append(f"- combined rows: {len(combined)} unique ids: {len(combined_ids)}")
    for key, df in parts.items():
        lines.append(f"- {key}: {len(df)} unique ids: {len(part_ids[key])}")
    if overlap_pairs:
        for a, b, n in overlap_pairs:
            lines.append(f"- ERROR overlap {a} ∩ {b}: {n} ids")
    else:
        lines.append("- split files are pairwise disjoint")
    lines.append(f"- ids in combined but in no split: {len(missing)}")
    lines.append(f"- ids in a split but not in combined: {len(extra)}")

    # label consistency on overlapping ids
    label_mismatches = 0
    combined_map = combined.set_index("sentence_id")["sentiment_label"]
    for key, df in parts.items():
        joined = df[["sentence_id", "sentiment_label"]].merge(
            combined_map.rename("combined_label"),
            left_on="sentence_id",
            right_index=True,
            how="inner",
        )
        label_mismatches += int((joined["sentiment_label"] != joined["combined_label"]).sum())
    lines.append(f"- label mismatches vs combined: {label_mismatches}")
    lines.append("")
    ok = (not overlap_pairs) and (not missing) and (not extra) and label_mismatches == 0
    return lines, ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    ensure_output_dir()

    zuco = read_csv(ZUCO_COMBINED_STANDARD)
    sst = read_csv(SST_COMBINED)
    sentences = read_csv(ZUCO_SENTENCES)

    zuco_lines, zuco_ok = _partition(
        "ZuCo 80/10/10 files",
        zuco,
        {
            "train.csv": read_csv(ZUCO_TRAIN),
            "valid.csv": read_csv(ZUCO_VALID),
            "test.csv": read_csv(ZUCO_TEST),
        },
    )
    sst_lines, sst_ok = _partition(
        "SST 80/10/10 files",
        sst,
        {
            "train_full_sst.csv": read_csv(SST_TRAIN),
            "valid_full_sst.csv": read_csv(SST_VALID),
            "test_full_sst.csv": read_csv(SST_TEST),
        },
    )

    zuco_ids = set(zuco["sentence_id"])
    sent_ids = set(sentences["sentence_id"])
    label_join = zuco[["sentence_id", "sentiment_label"]].merge(
        sentences, on="sentence_id", suffixes=("_combined", "_text")
    )
    text_ok = zuco_ids == sent_ids and (
        label_join["sentiment_label_combined"] == label_join["sentiment_label_text"]
    ).all()

    lines = [
        "# Split sanity check",
        "",
        "Generated by `examples/split_sanity_check.py`.",
        "",
    ]
    lines.extend(zuco_lines)
    lines.extend(sst_lines)
    lines.extend(
        [
            "## `ssts_ZuCo.csv` vs combined",
            "",
            f"- id sets equal: {zuco_ids == sent_ids}",
            f"- labels equal on the inner join: "
            f"{bool((label_join['sentiment_label_combined'] == label_join['sentiment_label_text']).all())}",
            "",
        ]
    )
    out = OUTPUT_DIR / "split_sanity_check.md"
    write_text(out, "\n".join(lines))
    print(f"Wrote {out}")
    print(f"zuco_partition_ok={zuco_ok} sst_partition_ok={sst_ok} text_ok={text_ok}")
    return 0 if (zuco_ok and sst_ok and text_ok) else 1


if __name__ == "__main__":
    raise SystemExit(main())
