"""Peek at word-level ZuCo averages and predicted SST gaze.

Prints a short reading of one ZuCo sentence and compares placeholder
`sst_et_test.csv` (all zeros) against `prediction_test_v2.csv`.
"""

from __future__ import annotations

import argparse

import pandas as pd

from common import (
    OUTPUT_DIR,
    PRED_TEST_V2,
    SST_FUSION_COLUMNS,
    SST_WORD_PLACEHOLDER,
    ZUCO_COMBINED_STANDARD,
    ZUCO_WORD_AVERAGE,
    ensure_output_dir,
    read_csv,
    write_text,
)


def _zuco_sentence(word_df: pd.DataFrame, sent_id: int = 0) -> pd.DataFrame:
    tag = f"{sent_id}_NR"
    return word_df[word_df["Sent_ID"] == tag].sort_values("Word_ID")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sentence-id", type=int, default=0)
    args = parser.parse_args()
    ensure_output_dir()

    words = read_csv(ZUCO_WORD_AVERAGE)
    zuco = read_csv(ZUCO_COMBINED_STANDARD)
    placeholder = read_csv(SST_WORD_PLACEHOLDER)
    predicted = read_csv(PRED_TEST_V2)

    preview = _zuco_sentence(words, args.sentence_id)
    sentence_row = zuco.loc[zuco["sentence_id"] == args.sentence_id]
    sentence_text = (
        sentence_row["sentence"].iloc[0] if len(sentence_row) else "(missing)"
    )

    ph_zero = (placeholder[SST_FUSION_COLUMNS] == 0).all().all()
    pred_zero = (predicted[SST_FUSION_COLUMNS] == 0).all().all()

    # Same skeleton?
    same_len = len(placeholder) == len(predicted)
    same_tokens = False
    if same_len:
        same_tokens = (
            placeholder["word"].fillna("").astype(str).reset_index(drop=True)
            == predicted["word"].fillna("").astype(str).reset_index(drop=True)
        ).mean()

    lines = [
        "# Word-level preview",
        "",
        "Generated by `examples/word_level_preview.py`.",
        "",
        f"## ZuCo sentence_id={args.sentence_id}",
        "",
        f"> {sentence_text}",
        "",
        f"Word-average rows for `Sent_ID={args.sentence_id}_NR`: {len(preview)}",
        "",
        "| Word_ID | Word | nFixations | FFD | GPT | TRT | GD | WordLen |",
        "| ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for _, row in preview.iterrows():
        token = str(row["Word"]).replace("|", "\\|")
        lines.append(
            f"| {int(row['Word_ID'])} | {token} | {row['nFixations']:.3f} | "
            f"{row['FFD']:.1f} | {row['GPT']:.1f} | {row['TRT']:.1f} | "
            f"{row['GD']:.1f} | {int(row['WordLen'])} |"
        )

    skipped = preview[preview["nFixations"] == 0]
    lines.extend(
        [
            "",
            f"Tokens with nFixations=0 in this average (often skipped function words): "
            f"{len(skipped)}",
            "",
            "## SST word tables",
            "",
            f"- `sst_et_test.csv` rows: {len(placeholder)}; all-zero gaze: {ph_zero}",
            f"- `prediction_test_v2.csv` rows: {len(predicted)}; all-zero gaze: {pred_zero}",
            f"- same row count: {same_len}",
            f"- token equality rate (if same length): {same_tokens}",
            "",
            "If you reduce predicted word gaze to a sentence vector, decide the",
            "reducer explicitly (mean of TRT, max of GPT, mean of all five, …).",
            "The checked-in SST sentence tables already contain one such reduce;",
            "this script does not invent a second one.",
            "",
        ]
    )
    out = OUTPUT_DIR / "word_level_preview.md"
    write_text(out, "\n".join(lines))
    preview.to_csv(OUTPUT_DIR / f"zuco_words_sentence_{args.sentence_id}.csv", index=False)
    print(f"Wrote {out}")
    print(f"ZuCo tokens for sentence {args.sentence_id}: {len(preview)}")
    print(f"placeholder all-zero={ph_zero} predicted all-zero={pred_zero}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
