"""Tiny markdown / HTML helpers for the generated lab book."""

from __future__ import annotations

from html import escape
from pathlib import Path


def md_table(headers: list[str], rows: list[list[object]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join("---" for _ in headers) + " |"
    body = "\n".join("| " + " | ".join(_cell(c) for c in row) + " |" for row in rows)
    return "\n".join((head, sep, body))


def _cell(value: object) -> str:
    if isinstance(value, float):
        if abs(value) >= 100:
            return f"{value:.2f}"
        return f"{value:.4f}"
    return str(value)


def html_page(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{escape(title)}</title>
  <style>
    :root {{
      --bg: #f6f1e7;
      --ink: #1f1a14;
      --card: #fffaf0;
      --accent: #8b3a2a;
      --muted: #5c5346;
      --line: #d9cbb3;
    }}
    html, body {{
      background: var(--bg);
      color: var(--ink);
      font: 16px/1.55 "Iowan Old Style", "Palatino Linotype", Palatino, serif;
      margin: 0;
    }}
    main {{
      max-width: 920px;
      margin: 0 auto;
      padding: 2.2rem 1.4rem 4rem;
    }}
    h1, h2, h3 {{ font-weight: 650; letter-spacing: -0.02em; }}
    h1 {{ font-size: 2.1rem; margin-bottom: 0.2rem; }}
    .lede {{ color: var(--muted); margin-top: 0; }}
    section {{
      background: var(--card);
      border: 1px solid var(--line);
      border-radius: 12px;
      padding: 1rem 1.2rem 1.2rem;
      margin: 1.1rem 0;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      font-size: 0.92rem;
    }}
    th, td {{
      border-bottom: 1px solid var(--line);
      padding: 0.35rem 0.45rem;
      text-align: left;
      vertical-align: top;
    }}
    th {{ color: var(--accent); }}
    code, pre {{
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.86rem;
    }}
    pre {{
      background: #efe6d4;
      padding: 0.8rem;
      overflow-x: auto;
      border-radius: 8px;
    }}
    .ok {{ color: #215c2a; }}
    .warn {{ color: var(--accent); }}
    footer {{ color: var(--muted); font-size: 0.88rem; }}
  </style>
</head>
<body>
<main>
<h1>{escape(title)}</h1>
{body}
<footer>Personal lab book for sapphireran/Transformer-Emotion-Analysis-with-Gaze. Generated by examples/10_build_labbook.py.</footer>
</main>
</body>
</html>
"""


def html_table(headers: list[str], rows: list[list[object]]) -> str:
    th = "".join(f"<th>{escape(str(h))}</th>" for h in headers)
    trs = []
    for row in rows:
        tds = "".join(f"<td>{escape(_cell(c))}</td>" for c in row)
        trs.append(f"<tr>{tds}</tr>")
    return f"<table><thead><tr>{th}</tr></thead><tbody>{''.join(trs)}</tbody></table>"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
